### ISSUE TITLE
Error in building package from source without rmarkdown and other packages

### ISSUE THREAD

**Issue by alistairdunn1** [quantifish/nzsf#10]
Add requirement for packages "rmarkdown", "tidyverse", "ggspatial", "viridis", l"wgeom", "rnaturalearthdata", and "patchwork" to allow (vignette) building from source (in cases where not installed).

**Comment by quantifish** [comment]
How did you try to install? Can you post the command so I can replicate? I tried from RStudio and using `devtools` (see https://github.com/quantifish/nzsf) and had no issues. No warnings spring up during `Check` either. All of those packages sit under the `suggests` section of the package.
