### ISSUE TITLE
get_standard_grid_origin ymin is wrong

### ISSUE THREAD

**Issue by quantifish** [quantifish/nzsf#14]
Not sure why but ymin in `get_standard_grid_origin` is way below the NZ EEZ in the vignette.

**Comment by quantifish** [comment]
`get_standard_grid_origin` out to return the number of cells in the x and y directions also so that they can be used to derive a raster later on also.

**Comment by cttedwards** [comment]
the ymin is at the bottom left corner of the grid. it is the start point for the grid, making sure the grid passes through the origin
